services:
  laravel:
    build:
    image: 
    networks:

    volumes:

    ports:

    working_dir: 
  redis:
    image: redis:alpine
    networks:

    volumes:

  mysqldb:
    image: 
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:

    networks:

    volumes:

networks:
  sysops:
    driver: bridge
volumes:
  mysqldbdata:
    driver: local
  redisdata:
    driver: local
